# Generated by Django 4.2.16 on 2024-11-22 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merek', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('stok', models.PositiveIntegerField(default=0)),
                ('harga_per_hari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(upload_to='motor_images/')),
                ('merek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='rental.merek')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16)),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('tanggal_pinjam', models.DateField(default=django.utils.timezone.now)),
                ('tanggal_kembali', models.DateField()),
                ('jumlah_bayar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sudah_bayar', models.BooleanField(default=False)),
                ('jumlah_denda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DIPESAN', 'Dipesan'), ('DIPINJAM', 'Dipinjam'), ('DIKEMBALIKAN', 'Dikembalikan')], default='DIPESAN', max_length=20)),
                ('no_polisi', models.CharField(max_length=20)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjamans', to='rental.motor')),
            ],
        ),
    ]
