# Generated by Django 4.2.16 on 2024-11-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='jumlah_denda',
        ),
    ]
